version: '3'
services:
  nginx:
    container_name: react-base-project-nginx
    build:
      dockerfile: Dockerfile.production
      context: .
    ports:
      - '80:80'
    environment:
      NODE_ENV: production
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro