version: '3'
services:
  app:
    container_name: react-base-project-app
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/share
    env_file:
      - .env
    ports:
      - "3000:3000"
