# PRODUCTION dockerfile.

FROM node:10.17-slim as build

RUN apt-get update

RUN mkdir -p /app
WORKDIR /app

ADD package.json /app/package.json
ADD package-lock.json /app/package-lock.json

RUN npm install

COPY ./ /app

RUN npm run build

FROM nginx:1.17
COPY --from=build /app/build /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]